//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace mialejandria.mifaro.data.Externo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class biblioDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new biblioDBEntities object using the connection string found in the 'biblioDBEntities' section of the application configuration file.
        /// </summary>
        public biblioDBEntities() : base("name=biblioDBEntities", "biblioDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new biblioDBEntities object.
        /// </summary>
        public biblioDBEntities(string connectionString) : base(connectionString, "biblioDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new biblioDBEntities object.
        /// </summary>
        public biblioDBEntities(EntityConnection connection) : base(connection, "biblioDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fondo> Fondos
        {
            get
            {
                if ((_Fondos == null))
                {
                    _Fondos = base.CreateObjectSet<Fondo>("Fondos");
                }
                return _Fondos;
            }
        }
        private ObjectSet<Fondo> _Fondos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Serie> Series
        {
            get
            {
                if ((_Series == null))
                {
                    _Series = base.CreateObjectSet<Serie>("Series");
                }
                return _Series;
            }
        }
        private ObjectSet<Serie> _Series;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UnidadDocumental> UnidadesDocumentales
        {
            get
            {
                if ((_UnidadesDocumentales == null))
                {
                    _UnidadesDocumentales = base.CreateObjectSet<UnidadDocumental>("UnidadesDocumentales");
                }
                return _UnidadesDocumentales;
            }
        }
        private ObjectSet<UnidadDocumental> _UnidadesDocumentales;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fondos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFondos(Fondo fondo)
        {
            base.AddObject("Fondos", fondo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Series EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeries(Serie serie)
        {
            base.AddObject("Series", serie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UnidadesDocumentales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnidadesDocumentales(UnidadDocumental unidadDocumental)
        {
            base.AddObject("UnidadesDocumentales", unidadDocumental);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="biblioDBModel", Name="Fondo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fondo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fondo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Fondo CreateFondo(global::System.Int32 id)
        {
            Fondo fondo = new Fondo();
            fondo.ID = id;
            return fondo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.String _Nivel;
        partial void OnNivelChanging(global::System.String value);
        partial void OnNivelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoReferencia
        {
            get
            {
                return _CodigoReferencia;
            }
            set
            {
                OnCodigoReferenciaChanging(value);
                ReportPropertyChanging("CodigoReferencia");
                _CodigoReferencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodigoReferencia");
                OnCodigoReferenciaChanged();
            }
        }
        private global::System.String _CodigoReferencia;
        partial void OnCodigoReferenciaChanging(global::System.String value);
        partial void OnCodigoReferenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodRefPadre
        {
            get
            {
                return _CodRefPadre;
            }
            set
            {
                OnCodRefPadreChanging(value);
                ReportPropertyChanging("CodRefPadre");
                _CodRefPadre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodRefPadre");
                OnCodRefPadreChanged();
            }
        }
        private global::System.String _CodRefPadre;
        partial void OnCodRefPadreChanging(global::System.String value);
        partial void OnCodRefPadreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="biblioDBModel", Name="Serie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Serie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Serie object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Serie CreateSerie(global::System.Int32 id)
        {
            Serie serie = new Serie();
            serie.ID = id;
            return serie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.String _Nivel;
        partial void OnNivelChanging(global::System.String value);
        partial void OnNivelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoReferencia
        {
            get
            {
                return _CodigoReferencia;
            }
            set
            {
                OnCodigoReferenciaChanging(value);
                ReportPropertyChanging("CodigoReferencia");
                _CodigoReferencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodigoReferencia");
                OnCodigoReferenciaChanged();
            }
        }
        private global::System.String _CodigoReferencia;
        partial void OnCodigoReferenciaChanging(global::System.String value);
        partial void OnCodigoReferenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodRefPadre
        {
            get
            {
                return _CodRefPadre;
            }
            set
            {
                OnCodRefPadreChanging(value);
                ReportPropertyChanging("CodRefPadre");
                _CodRefPadre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodRefPadre");
                OnCodRefPadreChanged();
            }
        }
        private global::System.String _CodRefPadre;
        partial void OnCodRefPadreChanging(global::System.String value);
        partial void OnCodRefPadreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="biblioDBModel", Name="UnidadDocumental")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UnidadDocumental : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UnidadDocumental object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static UnidadDocumental CreateUnidadDocumental(global::System.Int32 id)
        {
            UnidadDocumental unidadDocumental = new UnidadDocumental();
            unidadDocumental.ID = id;
            return unidadDocumental;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.String _Nivel;
        partial void OnNivelChanging(global::System.String value);
        partial void OnNivelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoReferencia
        {
            get
            {
                return _CodigoReferencia;
            }
            set
            {
                OnCodigoReferenciaChanging(value);
                ReportPropertyChanging("CodigoReferencia");
                _CodigoReferencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodigoReferencia");
                OnCodigoReferenciaChanged();
            }
        }
        private global::System.String _CodigoReferencia;
        partial void OnCodigoReferenciaChanging(global::System.String value);
        partial void OnCodigoReferenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodRefPadre
        {
            get
            {
                return _CodRefPadre;
            }
            set
            {
                OnCodRefPadreChanging(value);
                ReportPropertyChanging("CodRefPadre");
                _CodRefPadre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodRefPadre");
                OnCodRefPadreChanged();
            }
        }
        private global::System.String _CodRefPadre;
        partial void OnCodRefPadreChanging(global::System.String value);
        partial void OnCodRefPadreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VolumenSoporte
        {
            get
            {
                return _VolumenSoporte;
            }
            set
            {
                OnVolumenSoporteChanging(value);
                ReportPropertyChanging("VolumenSoporte");
                _VolumenSoporte = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VolumenSoporte");
                OnVolumenSoporteChanged();
            }
        }
        private global::System.String _VolumenSoporte;
        partial void OnVolumenSoporteChanging(global::System.String value);
        partial void OnVolumenSoporteChanged();

        #endregion
    
    }

    #endregion
    
}
